'use strict';
import '../css/main.css';
import '../img/logo.png';
import '../css/reset.css';
import ElementHeader from './class/classHeader.js';
import FilterEl from './class/classFilter.js';
const el = new ElementHeader();
el.renderHeader();
const fil = new FilterEl();
fil.renderFilterEl();
